Seize_mode: ["\\伊伴女鞋\\未完成\\待抠", "\\烟斗男鞋\\抠图", "\\千百度男鞋\\休闲\\未完成\\待抠", "\\千百度女鞋\\未完成\\待抠", "\\抠图"]
#Seize_mode: ["\\千百度女鞋\\2024\\5.17 白底\\1\\已修"]
cutouter01: ["\\伊伴女鞋\\未完成\\待抠", "\\烟斗男鞋\\抠图"]
cutouter02: ["\\千百度男鞋\\休闲\\未完成\\待抠"]
cutouter03: ["\\烟斗男鞋\\抠图"]
cutouter04: ["\\千百度女鞋\\未完成\\待抠"]