
Seize_mode: ["\\抠图", "\\抠图\\飞飞", "\\抠图\\琼瑶", "\\抠图\\小笠", "\\抠图\\孙洁", "\\抠图\\李强", "\\抠图\\海燕", "\\抠图\\其他（没有自己文件夹的放这里）"]
#Seize_mode: ["\\千百度女鞋\\2024\\5.17 白底\\1\\已修"]
cutouter01: ["\\伊伴女鞋\\未完成\\待抠", "\\烟斗男鞋\\抠图"]
cutouter02: ["\\千百度男鞋\\休闲\\未完成\\待抠"]
cutouter03: ["\\烟斗男鞋\\抠图"]
cutouter04: ["\\千百度女鞋\\未完成\\待抠"]